### ISSUE TITLE
no model file

### ISSUE THREAD

**Issue by daniilak** [OlivierNDO/image_proc#1]
SavedModel file does not exist at: cloud_scene_img_model_sgd_lrs_20191007_0313.hdf5/{saved_model.pbtxt|saved_model.pb}

Can you make the model publicly available or give it access by mail to daniilakk@gmail.com

For a dissertation at the university

**Comment by OlivierNDO** [comment]
My intention is not to share the trained model itself at this time. If you would like share more details about your idea (e.g. using the weights for transfer learning in a other application), I'd be interested to hear more via email.
